dist:     xenial
sudo:     required
language: cpp
os:       linux
compiler: gcc

script:
    - mkdir build
    - cd build
    - cmake ..
    - cpack --verbose --config CPackSourceConfig.cmake
    - ls -ls
    - tar -tf test-1.0.0-src.tar.xz
